import pygame
pygame.init()

class Piano(object):
    def __init__(self):
        self.A0=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A0.wav')
        self.A1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A1.wav')
        self.A2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A2.wav')
        self.A3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A3.wav')
        self.A4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A4.wav')
        self.A5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A5.wav')
        self.A6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A6.wav')
        self.A7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.A7.wav')
        self.Ab1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab1.wav')
        self.Ab2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab2.wav')
        self.Ab3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab3.wav')
        self.Ab4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab4.wav')
        self.Ab5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab5.wav')
        self.Ab6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab6.wav')
        self.Ab7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Ab7.wav')
        self.B0=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B0.wav')
        self.B1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B1.wav')
        self.B2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B2.wav')
        self.B3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B3.wav')
        self.B4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B4.wav')
        self.B5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B5.wav')
        self.B6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B6.wav')
        self.B7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.B7.wav')
        self.Bb0=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb0.wav')
        self.Bb1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb1.wav')
        self.Bb2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb2.wav')
        self.Bb3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb3.wav')
        self.Bb4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb4.wav')
        self.Bb5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb5.wav')
        self.Bb6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb6.wav')
        self.Bb7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Bb7.wav')
        self.C1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C1.wav')
        self.C2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C2.wav')
        self.C3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C3.wav')
        self.C4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C4.wav')
        self.C5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C5.wav')
        self.C6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C6.wav')
        self.C7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C7.wav')
        self.C8=pygame.mixer.Sound(file='Piano WAV/Piano.ff.C8.wav')
        self.D1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D1.wav')
        self.D2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D2.wav')
        self.D3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D3.wav')
        self.D4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D4.wav')
        self.D5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D5.wav')
        self.D6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D6.wav')
        self.D7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.D7.wav')
        self.Db1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db1.wav')
        self.Db2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db2.wav')
        self.Db3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db3.wav')
        self.Db4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db4.wav')
        self.Db5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db5.wav')
        self.Db6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db6.wav')
        self.Db7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Db7.wav')
        self.E1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E1.wav')
        self.E2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E2.wav')
        self.E3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E3.wav')
        self.E4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E4.wav')
        self.E5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E5.wav')
        self.E6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E6.wav')
        self.E7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.E7.wav')
        self.Eb1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb1.wav')
        self.Eb2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb2.wav')
        self.Eb3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb3.wav')
        self.Eb4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb4.wav')
        self.Eb5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb5.wav')
        self.Eb6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb6.wav')
        self.Eb7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Eb7.wav')
        self.F1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F1.wav')
        self.F2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F2.wav')
        self.F3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F3.wav')
        self.F4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F4.wav')
        self.F5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F5.wav')
        self.F6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F6.wav')
        self.F7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.F7.wav')
        self.G1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G1.wav')
        self.G2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G2.wav')
        self.G3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G3.wav')
        self.G4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G4.wav')
        self.G5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G5.wav')
        self.G6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G6.wav')
        self.G7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.G7.wav')
        self.Gb1=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb1.wav')
        self.Gb2=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb2.wav')
        self.Gb3=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb3.wav')
        self.Gb4=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb4.wav')
        self.Gb5=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb5.wav')
        self.Gb6=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb6.wav')
        self.Gb7=pygame.mixer.Sound(file='Piano WAV/Piano.ff.Gb7.wav')
        self.notes=[]
        self.hscrollDX=0
        self.pianoGrid = pygame.image.load('Piano grid.png').convert_alpha()
        self.sx2,self.sx3=0,870
        self.scrollGrid=(self.sx2,0,self.sx3,350)
    
    def __str__(self):
            return "self.piano"


        

